<?php

namespace Database\Seeders;

use App\Models\EvaluasiA;
use Illuminate\Database\Seeder;

class EvaluasiASeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $soal_colect = collect([
            'soal_1' => [
                '\(2x+y+3z=8\)',
                '\(x+2z=6\)',
                '\(x+3y+2z=-25\)',
                '\(x+3y+z=5\)',
                '\(x+y+z=6\)',
                '\(3x+2y-4z=17\)',
                '\(a+2b+3c=-10\)',
                '\(2x+2y+5z=-15\)',
                '\(x-2y+z=-5\)',
                '\(3x+4y+4z=-1\)',
                'Jika tukang parkir mendapatkan uang sebesar Rp. 13.000 untuk 2 buah mobil, 1 motor dan 1 sepeda. Sedangkan untuk 4 motor dan 2 sepda tukang parkir mendapatkan uang sebesar Rp. 10.000. dan untuk 4 mobil, 4 motor dan 2 sepeda paman parkir mendapatkan Rp. 30.000. berapakah paman parkir mendapatkan uang apabila ada 20 mobil dan 35 motor dalam sehari ?',
                'Anang mempunyai toko kelontong yang menjual paketan beras A, beras B dan Beras C yang dijual sebagai berikut. Paketan 2 kg beras A, 1 kg beras B dan 1 kg beras C di jual seharga Rp. 15.000. Paketan 1 kg beras A, 2 kg beras B dan 2 kg beras C di jual seharga Rp. 18.000. Paketan 4 kg beras A, 2 kg beras  dan 3 kg beras C di jual seharga Rp. 35.000. Hitunglah harga tiap kg beras A, B dan C !',
                'Jumlah uang Bambang, Burhan dan Budi adalah Rp. 150.000. jika uang Bambang dan Burhan adalah Rp. 250.000 dikurangi dua kali uang Budi. Sedangkan apabila uang Bambang dan Budi akan menghasilkan Rp. 30.000 lebih dari tiga kali uang Burhan. Berapakah uang Bambang dan Burhan ?',
                'Ucup beserta 2 temannya pergi ke toko buku. Ucup membeli 3 buku tulis, 2 buah pulpen dan 1 buah pensil seharga Rp. 41.000. burhan membeli 1 buku tulis, 2 pulpen dan 4 pensil seharga Rp. 25.000. bambang membeli 2 buku tulis, 3 pulpen dan 1 buah pensil seharga Rp. 33.000. berapakah harga buku tulis, pulpen dan pensil ?',
                'Diketahui sebuah bilangan tiga angka. Jumlah angka – angka tersebut adalah 12. Angka pertama ditambah angka kedua menghasilkan angka ketiga. Dua kali angka pertama di tambah angka kedua menghasilkan 16 di kurang angka ketiga. Berapakah hasil angka kedua di kurang angka ketiga ?',
                'Toko permen menjual merk permen x, y dan z. Harga semua permen satu persatu kalau digabung adalah Rp. 3500. Harga satu lusin permen x sama dengan setengah lusin permen z. Harga dua buah permen y sama dengan permen x. Berapakah harga dari empat permen x, dua permen y dan dua permen z ?',
                'Ucup mempunyai toko buah yang menjual paketan buah yang dijual sebagai berikut. Paket A mempunyai 2 kg apel malang, 1 kg alpukat mentega dan 3 kg jeruk baby seharga Rp. 204.000. Paket B mempunyai 4 kg apel malang, 2 kg alpukat mentega dan 3 kg jeruk baby seharga Rp. 308.000. Paket C mempunyai 1 kg apel malang, 4 kg alpukat mentega dan 2 kg jeruk baby seharga Rp. 231.000. Hitunglah harga tiap kg dari masing – masing buah !',
                'Dengan suatu alasan tertentu, 3 siswa yaitu Bambang, Burhan dan Zainal mengukur berat badan mereka. Berat badan mereka bertiga 195 kg. Berat badan Bambang dan Burhan adalah 150 kg. Sedangkan berat badan Zainal dan Bambang adalah 105 kg. Berapakah berat masing – masing orang ?',
                'Dalam sebuah perusahaan percetakan baju (sablon baju). Ada tiga macam alat produksi yang berjalan secara bersamaan yaitu alat A, B, dan C. Dalam satu jam ketiga alat produksi tersebut bisa menyablon baju sebanyak 26 buah baju. Alat A dan C dapat menyablon baju sebanyak alat B dalam satu jam. Dan alat B dan C dapat menyablon baju sebanyak 19 buah baju dalam satu jam. Berapa banyak produksi sablon baju dari alat A, B, dan C  dalam satu jam ?',
                'Jika sebuah komputer menjual varian laptop yaitu laptop merek asur, asem, dan lehnono. Jika Ucup membeli ketiga barang tersebut maka ucup harus membayar sebesar Rp. 22.600.000. Jika Bambang membeli laptop sebanyak 2 buah merek asur, 3 buah merek asem, dan 1 buah merek lehnono maka Bambang harus mengeluarkan uang sebesar Rp. 45.600.000. Jika Zainal membeli laptop tersebut sebanyak 4 buah merek asur, 1 buah merek asem, dan 2 buah merek lehnono maka Zainal harus mengeluarkan uang sebanyak Rp. 51.200.000. berapa harga apabila Burhan membeli 10 buah merek asem dan 8 buah merek lehnono ?',
            ],
            'soal_2' => [
                '\(x-3y-2z=4\)',
                '\(3x+2y+z=32\)',
                '\(3x-2y+5z=-7\)',
                '\(4x-2y-2z=4\)',
                '\(3x-y-2z=5\)',
                '\(3y+2z=-19\)',
                '\(a+3b+c=11\)',
                '\(3x+y+z=18\)',
                '\(2x+4y-3z=1\)',
                '\(x+4y+z=-17\)',
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
            ],
            'soal_3' => [
                '\(2x+2y+z=2\)',
                '\(2x+y+z=20\)',
                '\(2x+y-3z=-6\)',
                '\(x-y-4z=7\)',
                '\(2x+3y-z=4\)',
                '\(-x+2z=-11\)',
                '\(3a-b+2c=-9\)',
                '\(x-5y-6z=15\)',
                '\(4x-3y+4z=-10\)',
                '\(2x+y+z=6\)',
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
            ],
            'pertanyaan' => [
                'Berapakah nilai x dan y ?',
                'Berapakah nilai y+z ?',
                'Berapakah nilai z ?',
                'Berapakah nilai x+y-z ?',
                'Berapakah nilai x-y-z ?',
                'Berapakah nilai dari y ?',
                'Berapakah nilai a-b+c ?',
                'Berapakah nilai dari x,y dan z ?',
                'Berapakah nilai 2x+3y-z ?',
                'Berapakah nilai z- y ?',
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
            ],
            'pilihan_a' => [
                '\((-3,2)\)',
                '\(0\)',
                '\(-1\)',
                '\(7\)',
                '\(2\)',
                '\(6\)',
                '\(1\)',
                '\({(6,9,-9)}\)',
                '\(-1\)',
                '\(-2\)',
                '\(Rp. 170.000\)',
                '\((7.000,5.000,6.000)\)',
                '46.000 dan 80.000',
                '6.500, 3.000 dan 7.000',
                '\(-4\)',
                '\(9500\)',
                '\((16000,51000,42000)\)',
                '\((60,90,45)\)',
                '\((8,14,6)\)',
                '\(Rp. 142.000.000\)',
            ],
            'pilihan_b' => [
                '\((2,-2)\)',
                '\(-1\)',
                '\(2\)',
                '\(3\)',
                '\(-2\)',
                '\(-3\)',
                '\(8\)',
                '\({(-12,-4,2)}\)',
                '\(-8\)',
                '\(2\)',
                '\(Rp. 214.000\)',
                '\((7.700,6.500,5.900)\)',
                '30.000 dan 60.000',
                '2.900, 10.000 dan 5.000',
                '\(-5\)',
                '\(7000\)',
                '\((5000,59000,44000)\)',
                '\((50,69,59)\)',
                '\((7,15,8)\)',
                '\(Rp. 137.000.000\)',
            ],
            'pilihan_c' => [
                '\((-1,4)\)',
                '\(3\)',
                '\(3\)',
                '\(1\)',
                '\(-1\)',
                '\(-4\)',
                '\(-9\)',
                '\({(7,-12,8)}\)',
                '\(2\)',
                '\(-6\)',
                '\(Rp. 134.000\)',
                '\((4.000,2.000,5.000)\)',
                '23.000 dan 10.000',
                '8.200, 1.000 dan 3.400',
                '\(7\)',
                '\(14000\)',
                '\((92000,7000,36000)\)',
                '\((77,97,61)\)',
                '\((7,13,6)\)',
                '\(Rp. 140.800.000\)',
            ],
            'pilihan_d' => [
                '\((1,-3)\)',
                '\(6\)',
                '\(-4\)',
                '\(5\)',
                '\(-5\)',
                '\(5\)',
                '\(-10\)',
                '\({(-1,9,-1)}\)',
                '\(1\)',
                '\(4\)',
                '\(Rp. 191.000\)',
                '\((3.000,2.300,4.000)\)',
                '23.000 dan 21.000',
                '11.000, 3.000 dan 2.000',
                '\(-3\)',
                '\(9000\)',
                '\((55000,34000,20000)\)',
                '\((78,77,61)\)',
                '\((8,18,10)\)',
                '\(Rp. 121.000.000\)',
            ],
            'pilihan_e' => [
                '\((3,-4)\)',
                '\(5\)',
                '\(-2\)',
                '\(0\)',
                '\(4\)',
                '\(-5\)',
                '\(-2\)',
                '\({(20,-18,12)}\)',
                '\(3\)',
                '\(8\)',
                '\(Rp. 192.000\)',
                '\((2.000,7.000,6.900)\)',
                '20.000 dan 30.000',
                '9.000, 2.600 dan 1.300',
                '\(0\)',
                '\(10000\)',
                '\((91000,4000,79000)\)',
                '\((54,96,75)\)',
                '\((8,20,12)\)',
                '\(Rp. 120.200.000\)',
            ],
            'jawaban' => [
                'b',
                'a',
                'e',
                'd',
                'a',
                'b',
                'c',
                'a',
                'd',
                'e',
                'a',
                'c',
                'e',
                'd',
                'a',
                'd',
                'd',
                'a',
                'c',
                'c',
            ],
        ]);
        $i = 0;
        while ($i < 20) {
            EvaluasiA::insert([
                'soal_1' => $soal_colect['soal_1'][$i],
                'soal_2' => $soal_colect['soal_2'][$i],
                'soal_3' => $soal_colect['soal_3'][$i],
                'pertanyaan' => $soal_colect['pertanyaan'][$i],
                'pilihan_a' => $soal_colect['pilihan_a'][$i],
                'pilihan_b' => $soal_colect['pilihan_b'][$i],
                'pilihan_c' => $soal_colect['pilihan_c'][$i],
                'pilihan_d' => $soal_colect['pilihan_d'][$i],
                'pilihan_e' => $soal_colect['pilihan_e'][$i],
                'jawaban' => $soal_colect['jawaban'][$i],

            ]);
            $i++;
        }
    }
}
